# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-11-29 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rsa_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploytask',
            name='branch',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='分支'),
        ),
        migrations.AlterField(
            model_name='deploytask',
            name='commit',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='提交记录'),
        ),
        migrations.AlterField(
            model_name='deploytask',
            name='tag',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='版本'),
        ),
    ]
