# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-01 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_deploytask_deploy_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploytask',
            name='deploy_server',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Server', verbose_name='自定义服务器'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deploytask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '待发布'), (2, '发布中'), (3, '成功'), (4, '失败')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='projectenv',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Project', verbose_name='项目'),
        ),
    ]
