# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-01 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20191201_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploytask',
            name='deploy_server',
        ),
    ]
